name: Demo action

on: [push]
# on: 
#   push:
#     tags:
#       - "v*"

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: thing

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Build
      - name: Build the application with node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: |
          npm i
          npm run build

      # Login ghcr
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Meta data
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     tags: |
      #       type=semver,pattern={{version}}

      # build and label
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: sample-1.0.0
          labels: ${{ steps.meta.outputs.labels }}
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}

      # Deployment
      # - name: Remote ssh deployment
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EDGE_ADDRESS }}
      #     username: ${{ secrets.EDGE_USERNAME }}
      #     key: ${{ secrets.EDGE_RSA }}
      #     port: ${{ secrets.EDGE_PORT }}
      #     script: |
      #       docker pull ghcr.io/allochi/sample:latest
      #       docker rm -f sample
      #       docker run -d --network=caddy --name=sample ghcr.io/allochi/sample:latest
